import { MigrationInterface, QueryRunner } from "typeorm";

export class Migration1778344985431 implements MigrationInterface {
    name = 'Migration1778344985431'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_users_branch_id"`);
        await queryRunner.query(`ALTER TABLE "branch_coa_accounts" DROP CONSTRAINT "FK_bca_branch_id"`);
        await queryRunner.query(`ALTER TABLE "branch_coa_accounts" DROP CONSTRAINT "FK_bca_teller_fc_coa"`);
        await queryRunner.query(`ALTER TABLE "branch_coa_accounts" DROP CONSTRAINT "FK_bca_teller_usd_coa"`);
        await queryRunner.query(`ALTER TABLE "branch_coa_accounts" DROP CONSTRAINT "FK_bca_vault_fc_coa"`);
        await queryRunner.query(`ALTER TABLE "branch_coa_accounts" DROP CONSTRAINT "FK_bca_vault_usd_coa"`);
        await queryRunner.query(`ALTER TABLE "teller_coa_accounts" DROP CONSTRAINT "FK_teller_coa_accounts_fc_coa"`);
        await queryRunner.query(`ALTER TABLE "teller_coa_accounts" DROP CONSTRAINT "FK_teller_coa_accounts_teller"`);
        await queryRunner.query(`ALTER TABLE "teller_coa_accounts" DROP CONSTRAINT "FK_teller_coa_accounts_usd_coa"`);
        await queryRunner.query(`ALTER TABLE "teller_sessions" DROP CONSTRAINT "FK_teller_sessions_approver"`);
        await queryRunner.query(`ALTER TABLE "teller_sessions" DROP CONSTRAINT "FK_teller_sessions_branch"`);
        await queryRunner.query(`ALTER TABLE "teller_sessions" DROP CONSTRAINT "FK_teller_sessions_teller"`);
        await queryRunner.query(`ALTER TABLE "teller_transactions" DROP CONSTRAINT "FK_teller_transactions_session"`);
        await queryRunner.query(`ALTER TABLE "teller_transactions" DROP CONSTRAINT "FK_teller_tx_account_id"`);
        await queryRunner.query(`ALTER TABLE "client_transactions" DROP CONSTRAINT "FK_client_tx_account_id"`);
        await queryRunner.query(`ALTER TABLE "client_transactions" DROP CONSTRAINT "FK_client_tx_branch_id"`);
        await queryRunner.query(`ALTER TABLE "client_transactions" DROP CONSTRAINT "FK_client_tx_performed_by"`);
        await queryRunner.query(`ALTER TABLE "transfers" DROP CONSTRAINT "FK_transfers_credit_tx"`);
        await queryRunner.query(`ALTER TABLE "transfers" DROP CONSTRAINT "FK_transfers_debit_tx"`);
        await queryRunner.query(`ALTER TABLE "session_denominations" DROP CONSTRAINT "FK_session_denoms_session_id"`);
        await queryRunner.query(`ALTER TABLE "remittances" DROP CONSTRAINT "FK_remittances_cancelled_by"`);
        await queryRunner.query(`ALTER TABLE "remittances" DROP CONSTRAINT "FK_remittances_payout_session"`);
        await queryRunner.query(`ALTER TABLE "remittances" DROP CONSTRAINT "FK_remittances_payout_teller"`);
        await queryRunner.query(`ALTER TABLE "remittances" DROP CONSTRAINT "FK_remittances_receiving_branch"`);
        await queryRunner.query(`ALTER TABLE "remittances" DROP CONSTRAINT "FK_remittances_sending_branch"`);
        await queryRunner.query(`ALTER TABLE "remittances" DROP CONSTRAINT "FK_remittances_sending_session"`);
        await queryRunner.query(`ALTER TABLE "remittances" DROP CONSTRAINT "FK_remittances_sending_teller"`);
        await queryRunner.query(`ALTER TABLE "loans" DROP CONSTRAINT "FK_loans_account_id"`);
        await queryRunner.query(`ALTER TABLE "loans" DROP CONSTRAINT "FK_loans_applied_by"`);
        await queryRunner.query(`ALTER TABLE "loans" DROP CONSTRAINT "FK_loans_branch_id"`);
        await queryRunner.query(`ALTER TABLE "loans" DROP CONSTRAINT "FK_loans_client_id"`);
        await queryRunner.query(`ALTER TABLE "loans" DROP CONSTRAINT "FK_loans_disbursed_by"`);
        await queryRunner.query(`ALTER TABLE "loans" DROP CONSTRAINT "FK_loans_reviewed_by"`);
        await queryRunner.query(`ALTER TABLE "loan_repayment_schedules" DROP CONSTRAINT "FK_schedules_loan_id"`);
        await queryRunner.query(`ALTER TABLE "loan_payments" DROP CONSTRAINT "FK_loan_payments_recorded_by"`);
        await queryRunner.query(`ALTER TABLE "loan_payments" DROP CONSTRAINT "FK_loan_payments_transaction_id"`);
        await queryRunner.query(`ALTER TABLE "loan_payments" DROP CONSTRAINT "FK_payments_loan_id"`);
        await queryRunner.query(`ALTER TABLE "loan_payments" DROP CONSTRAINT "FK_payments_schedule_id"`);
        await queryRunner.query(`ALTER TABLE "loan_penalties" DROP CONSTRAINT "FK_penalties_loan_id"`);
        await queryRunner.query(`ALTER TABLE "loan_penalties" DROP CONSTRAINT "FK_penalties_schedule_id"`);
        await queryRunner.query(`ALTER TABLE "loan_reminders" DROP CONSTRAINT "FK_loan_reminders_loan"`);
        await queryRunner.query(`ALTER TABLE "loan_reminders" DROP CONSTRAINT "FK_loan_reminders_schedule"`);
        await queryRunner.query(`ALTER TABLE "loan_documents" DROP CONSTRAINT "FK_loan_docs_uploaded_by"`);
        await queryRunner.query(`ALTER TABLE "loan_documents" DROP CONSTRAINT "FK_loan_documents_loan_id"`);
        await queryRunner.query(`ALTER TABLE "client_documents" DROP CONSTRAINT "FK_client_docs_client_id"`);
        await queryRunner.query(`ALTER TABLE "client_documents" DROP CONSTRAINT "FK_client_docs_reviewed_by"`);
        await queryRunner.query(`ALTER TABLE "client_documents" DROP CONSTRAINT "FK_client_docs_uploaded_by"`);
        await queryRunner.query(`ALTER TABLE "representative_documents" DROP CONSTRAINT "FK_rep_docs_rep_id"`);
        await queryRunner.query(`ALTER TABLE "representative_documents" DROP CONSTRAINT "FK_rep_docs_reviewed_by"`);
        await queryRunner.query(`ALTER TABLE "representative_documents" DROP CONSTRAINT "FK_rep_docs_uploaded_by"`);
        await queryRunner.query(`ALTER TABLE "organization_representative_documents" DROP CONSTRAINT "FK_org_rep_docs_rep_id"`);
        await queryRunner.query(`ALTER TABLE "organization_representative_documents" DROP CONSTRAINT "FK_org_rep_docs_reviewed_by"`);
        await queryRunner.query(`ALTER TABLE "organization_representative_documents" DROP CONSTRAINT "FK_org_rep_docs_uploaded_by"`);
        await queryRunner.query(`ALTER TABLE "guardian_documents" DROP CONSTRAINT "FK_guardian_docs_guardian_id"`);
        await queryRunner.query(`ALTER TABLE "guardian_documents" DROP CONSTRAINT "FK_guardian_docs_reviewed_by"`);
        await queryRunner.query(`ALTER TABLE "guardian_documents" DROP CONSTRAINT "FK_guardian_docs_uploaded_by"`);
        await queryRunner.query(`ALTER TABLE "clients" DROP CONSTRAINT "FK_clients_branch_id"`);
        await queryRunner.query(`ALTER TABLE "clients" DROP CONSTRAINT "FK_clients_created_by"`);
        await queryRunner.query(`ALTER TABLE "clients" DROP CONSTRAINT "FK_clients_kyc_reviewed_by"`);
        await queryRunner.query(`ALTER TABLE "organization_profiles" DROP CONSTRAINT "FK_5f629e15d16b419e7d1b8774b45"`);
        await queryRunner.query(`ALTER TABLE "accounts" DROP CONSTRAINT "FK_accounts_branch_id"`);
        await queryRunner.query(`ALTER TABLE "accounts" DROP CONSTRAINT "FK_accounts_client_id"`);
        await queryRunner.query(`ALTER TABLE "accounts" DROP CONSTRAINT "FK_accounts_opened_by"`);
        await queryRunner.query(`ALTER TABLE "chart_of_accounts" DROP CONSTRAINT "chart_of_accounts_created_by_fkey"`);
        await queryRunner.query(`ALTER TABLE "chart_of_accounts" DROP CONSTRAINT "chart_of_accounts_parent_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "journal_entries" DROP CONSTRAINT "FK_journal_entries_branch"`);
        await queryRunner.query(`ALTER TABLE "journal_entries" DROP CONSTRAINT "FK_journal_entries_performer"`);
        await queryRunner.query(`ALTER TABLE "journal_entries" DROP CONSTRAINT "journal_entries_posted_by_fkey"`);
        await queryRunner.query(`ALTER TABLE "journal_entries" DROP CONSTRAINT "journal_entries_reversal_of_fkey"`);
        await queryRunner.query(`ALTER TABLE "journal_entries" DROP CONSTRAINT "journal_entries_transaction_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "journal_lines" DROP CONSTRAINT "FK_journal_lines_account"`);
        await queryRunner.query(`ALTER TABLE "journal_lines" DROP CONSTRAINT "FK_journal_lines_entry"`);
        await queryRunner.query(`DROP INDEX "public"."idx_session_denominations_session_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_remittances_receiving_branch_status"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_remittances_sending_branch"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_loan_reminders_loan_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_loan_reminders_schedule_id"`);
        await queryRunner.query(`ALTER TABLE "loans" DROP COLUMN "form_fee"`);
        await queryRunner.query(`ALTER TABLE "loan_repayment_schedules" DROP COLUMN "reminder_sent_at"`);
        await queryRunner.query(`ALTER TYPE "public"."users_role_enum" RENAME TO "users_role_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."users_role_enum" AS ENUM('TELLER', 'LOAN_OFFICER', 'LOAN_APPROVER', 'BRANCH_MANAGER', 'HEAD_CASHIER', 'HQ_MANAGER', 'ADMIN')`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "role" TYPE "public"."users_role_enum" USING "role"::"text"::"public"."users_role_enum"`);
        await queryRunner.query(`DROP TYPE "public"."users_role_enum_old"`);
        await queryRunner.query(`ALTER TABLE "teller_coa_accounts" ALTER COLUMN "branch_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "client_transactions" DROP CONSTRAINT "UQ_transactions_reference"`);
        await queryRunner.query(`ALTER TABLE "transfers" ALTER COLUMN "fee_amount" DROP DEFAULT`);
        await queryRunner.query(`ALTER TYPE "public"."loan_currency_enum" RENAME TO "loan_currency_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."loans_currency_enum" AS ENUM('USD', 'FC')`);
        await queryRunner.query(`ALTER TABLE "loans" ALTER COLUMN "currency" TYPE "public"."loans_currency_enum" USING "currency"::"text"::"public"."loans_currency_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."loans_status_enum" RENAME TO "loans_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."loans_status_enum" AS ENUM('PENDING', 'APPROVED', 'REJECTED', 'ACTIVE', 'CLOSED', 'WATCH', 'SUBSTANDARD', 'DOUBTFUL', 'LOSS', 'WRITE_OFF')`);
        await queryRunner.query(`ALTER TABLE "loans" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "loans" ALTER COLUMN "status" TYPE "public"."loans_status_enum" USING "status"::"text"::"public"."loans_status_enum"`);
        await queryRunner.query(`ALTER TABLE "loans" ALTER COLUMN "status" SET DEFAULT 'PENDING'`);
        await queryRunner.query(`DROP TYPE "public"."loans_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."loan_payments_currency_enum" AS ENUM('USD', 'FC')`);
        await queryRunner.query(`ALTER TABLE "loan_payments" ALTER COLUMN "currency" TYPE "public"."loan_payments_currency_enum" USING "currency"::"text"::"public"."loan_payments_currency_enum"`);
        await queryRunner.query(`DROP TYPE "public"."loan_currency_enum_old"`);
        await queryRunner.query(`ALTER TABLE "loan_payments" ALTER COLUMN "payment_date" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "loan_penalties" ALTER COLUMN "applied_at" DROP DEFAULT`);
        await queryRunner.query(`ALTER TYPE "public"."reminder_channel_enum" RENAME TO "reminder_channel_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."loan_reminders_channel_enum" AS ENUM('EMAIL', 'SMS')`);
        await queryRunner.query(`ALTER TABLE "loan_reminders" ALTER COLUMN "channel" TYPE "public"."loan_reminders_channel_enum" USING "channel"::"text"::"public"."loan_reminders_channel_enum"`);
        await queryRunner.query(`DROP TYPE "public"."reminder_channel_enum_old"`);
        await queryRunner.query(`ALTER TYPE "public"."reminder_status_enum" RENAME TO "reminder_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."loan_reminders_status_enum" AS ENUM('SENT', 'FAILED')`);
        await queryRunner.query(`ALTER TABLE "loan_reminders" ALTER COLUMN "status" TYPE "public"."loan_reminders_status_enum" USING "status"::"text"::"public"."loan_reminders_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."reminder_status_enum_old"`);
        await queryRunner.query(`ALTER TYPE "public"."loan_document_type_enum" RENAME TO "loan_document_type_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."loan_documents_document_type_enum" AS ENUM('MOU', 'COMMITMENT_LETTER', 'REQUEST_LETTER')`);
        await queryRunner.query(`ALTER TABLE "loan_documents" ALTER COLUMN "document_type" TYPE "public"."loan_documents_document_type_enum" USING "document_type"::"text"::"public"."loan_documents_document_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."loan_document_type_enum_old"`);
        await queryRunner.query(`ALTER TYPE "public"."representative_documents_document_type_enum" RENAME TO "representative_documents_document_type_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."representative_documents_document_type_enum" AS ENUM('PASSPORT_PHOTO', 'ID_DOCUMENT', 'REPRESENTATIVE_ID', 'SIGNATURE')`);
        await queryRunner.query(`ALTER TABLE "representative_documents" ALTER COLUMN "document_type" TYPE "public"."representative_documents_document_type_enum" USING "document_type"::"text"::"public"."representative_documents_document_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."representative_documents_document_type_enum_old"`);
        await queryRunner.query(`ALTER TYPE "public"."organization_representative_documents_document_type_enum" RENAME TO "organization_representative_documents_document_type_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."organization_representative_documents_document_type_enum" AS ENUM('PASSPORT_PHOTO', 'ID_DOCUMENT', 'SIGNATURE')`);
        await queryRunner.query(`ALTER TABLE "organization_representative_documents" ALTER COLUMN "document_type" TYPE "public"."organization_representative_documents_document_type_enum" USING "document_type"::"text"::"public"."organization_representative_documents_document_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."organization_representative_documents_document_type_enum_old"`);
        await queryRunner.query(`ALTER TABLE "chart_of_accounts" ADD CONSTRAINT "FK_233c2a470511f11b1564bb6cd1e" FOREIGN KEY ("parent_id") REFERENCES "chart_of_accounts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "journal_lines" ADD CONSTRAINT "FK_1fd23ae91f0c24764b4e581c72e" FOREIGN KEY ("journal_entry_id") REFERENCES "journal_entries"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "journal_lines" ADD CONSTRAINT "FK_46bed88ea929e6f0aa17bf20845" FOREIGN KEY ("account_id") REFERENCES "chart_of_accounts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "journal_lines" DROP CONSTRAINT "FK_46bed88ea929e6f0aa17bf20845"`);
        await queryRunner.query(`ALTER TABLE "journal_lines" DROP CONSTRAINT "FK_1fd23ae91f0c24764b4e581c72e"`);
        await queryRunner.query(`ALTER TABLE "chart_of_accounts" DROP CONSTRAINT "FK_233c2a470511f11b1564bb6cd1e"`);
        await queryRunner.query(`CREATE TYPE "public"."organization_representative_documents_document_type_enum_old" AS ENUM('PASSPORT_PHOTO', 'ID_DOCUMENT')`);
        await queryRunner.query(`ALTER TABLE "organization_representative_documents" ALTER COLUMN "document_type" TYPE "public"."organization_representative_documents_document_type_enum_old" USING "document_type"::"text"::"public"."organization_representative_documents_document_type_enum_old"`);
        await queryRunner.query(`DROP TYPE "public"."organization_representative_documents_document_type_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."organization_representative_documents_document_type_enum_old" RENAME TO "organization_representative_documents_document_type_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."representative_documents_document_type_enum_old" AS ENUM('PASSPORT_PHOTO', 'ID_DOCUMENT', 'REPRESENTATIVE_ID')`);
        await queryRunner.query(`ALTER TABLE "representative_documents" ALTER COLUMN "document_type" TYPE "public"."representative_documents_document_type_enum_old" USING "document_type"::"text"::"public"."representative_documents_document_type_enum_old"`);
        await queryRunner.query(`DROP TYPE "public"."representative_documents_document_type_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."representative_documents_document_type_enum_old" RENAME TO "representative_documents_document_type_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."loan_document_type_enum_old" AS ENUM('MOU', 'COMMITMENT_LETTER', 'REQUEST_LETTER')`);
        await queryRunner.query(`ALTER TABLE "loan_documents" ALTER COLUMN "document_type" TYPE "public"."loan_document_type_enum_old" USING "document_type"::"text"::"public"."loan_document_type_enum_old"`);
        await queryRunner.query(`DROP TYPE "public"."loan_documents_document_type_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."loan_document_type_enum_old" RENAME TO "loan_document_type_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."reminder_status_enum_old" AS ENUM('SENT', 'FAILED')`);
        await queryRunner.query(`ALTER TABLE "loan_reminders" ALTER COLUMN "status" TYPE "public"."reminder_status_enum_old" USING "status"::"text"::"public"."reminder_status_enum_old"`);
        await queryRunner.query(`DROP TYPE "public"."loan_reminders_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."reminder_status_enum_old" RENAME TO "reminder_status_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."reminder_channel_enum_old" AS ENUM('EMAIL', 'SMS')`);
        await queryRunner.query(`ALTER TABLE "loan_reminders" ALTER COLUMN "channel" TYPE "public"."reminder_channel_enum_old" USING "channel"::"text"::"public"."reminder_channel_enum_old"`);
        await queryRunner.query(`DROP TYPE "public"."loan_reminders_channel_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."reminder_channel_enum_old" RENAME TO "reminder_channel_enum"`);
        await queryRunner.query(`ALTER TABLE "loan_penalties" ALTER COLUMN "applied_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "loan_payments" ALTER COLUMN "payment_date" SET DEFAULT now()`);
        await queryRunner.query(`CREATE TYPE "public"."loan_currency_enum_old" AS ENUM('USD', 'FC')`);
        await queryRunner.query(`ALTER TABLE "loan_payments" ALTER COLUMN "currency" TYPE "public"."loan_currency_enum_old" USING "currency"::"text"::"public"."loan_currency_enum_old"`);
        await queryRunner.query(`DROP TYPE "public"."loan_payments_currency_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."loan_currency_enum_old" RENAME TO "loan_currency_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."loans_status_enum_old" AS ENUM('PENDING', 'APPROVED', 'REJECTED', 'ACTIVE', 'CLOSED', 'DEFAULTED', 'WATCH', 'SUBSTANDARD', 'DOUBTFUL', 'LOSS', 'WRITE_OFF')`);
        await queryRunner.query(`ALTER TABLE "loans" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "loans" ALTER COLUMN "status" TYPE "public"."loans_status_enum_old" USING "status"::"text"::"public"."loans_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "loans" ALTER COLUMN "status" SET DEFAULT 'PENDING'`);
        await queryRunner.query(`DROP TYPE "public"."loans_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."loans_status_enum_old" RENAME TO "loans_status_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."loan_currency_enum_old" AS ENUM('USD', 'FC')`);
        await queryRunner.query(`ALTER TABLE "loans" ALTER COLUMN "currency" TYPE "public"."loan_currency_enum_old" USING "currency"::"text"::"public"."loan_currency_enum_old"`);
        await queryRunner.query(`DROP TYPE "public"."loans_currency_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."loan_currency_enum_old" RENAME TO "loan_currency_enum"`);
        await queryRunner.query(`ALTER TABLE "transfers" ALTER COLUMN "fee_amount" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "client_transactions" ADD CONSTRAINT "UQ_transactions_reference" UNIQUE ("reference")`);
        await queryRunner.query(`ALTER TABLE "teller_coa_accounts" ALTER COLUMN "branch_id" DROP NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."users_role_enum_old" AS ENUM('TELLER', 'LOAN_OFFICER', 'BRANCH_MANAGER', 'ADMIN', 'HQ_MANAGER', 'HEAD_CASHIER')`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "role" TYPE "public"."users_role_enum_old" USING "role"::"text"::"public"."users_role_enum_old"`);
        await queryRunner.query(`DROP TYPE "public"."users_role_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."users_role_enum_old" RENAME TO "users_role_enum"`);
        await queryRunner.query(`ALTER TABLE "loan_repayment_schedules" ADD "reminder_sent_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "loans" ADD "form_fee" numeric(18,2) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`CREATE INDEX "IDX_loan_reminders_schedule_id" ON "loan_reminders" ("schedule_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_loan_reminders_loan_id" ON "loan_reminders" ("loan_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_remittances_sending_branch" ON "remittances" ("sending_branch_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_remittances_receiving_branch_status" ON "remittances" ("receiving_branch_id", "status") `);
        await queryRunner.query(`CREATE INDEX "idx_session_denominations_session_id" ON "session_denominations" ("session_id") `);
        await queryRunner.query(`ALTER TABLE "journal_lines" ADD CONSTRAINT "FK_journal_lines_entry" FOREIGN KEY ("journal_entry_id") REFERENCES "journal_entries"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "journal_lines" ADD CONSTRAINT "FK_journal_lines_account" FOREIGN KEY ("account_id") REFERENCES "chart_of_accounts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "journal_entries" ADD CONSTRAINT "journal_entries_transaction_id_fkey" FOREIGN KEY ("transaction_id") REFERENCES "client_transactions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "journal_entries" ADD CONSTRAINT "journal_entries_reversal_of_fkey" FOREIGN KEY ("reversal_of") REFERENCES "journal_entries"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "journal_entries" ADD CONSTRAINT "journal_entries_posted_by_fkey" FOREIGN KEY ("posted_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "journal_entries" ADD CONSTRAINT "FK_journal_entries_performer" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "journal_entries" ADD CONSTRAINT "FK_journal_entries_branch" FOREIGN KEY ("branch_id") REFERENCES "branches"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chart_of_accounts" ADD CONSTRAINT "chart_of_accounts_parent_id_fkey" FOREIGN KEY ("parent_id") REFERENCES "chart_of_accounts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chart_of_accounts" ADD CONSTRAINT "chart_of_accounts_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "accounts" ADD CONSTRAINT "FK_accounts_opened_by" FOREIGN KEY ("opened_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "accounts" ADD CONSTRAINT "FK_accounts_client_id" FOREIGN KEY ("client_id") REFERENCES "clients"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "accounts" ADD CONSTRAINT "FK_accounts_branch_id" FOREIGN KEY ("branch_id") REFERENCES "branches"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "organization_profiles" ADD CONSTRAINT "FK_5f629e15d16b419e7d1b8774b45" FOREIGN KEY ("client_id") REFERENCES "clients"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "clients" ADD CONSTRAINT "FK_clients_kyc_reviewed_by" FOREIGN KEY ("kyc_reviewed_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "clients" ADD CONSTRAINT "FK_clients_created_by" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "clients" ADD CONSTRAINT "FK_clients_branch_id" FOREIGN KEY ("branch_id") REFERENCES "branches"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "guardian_documents" ADD CONSTRAINT "FK_guardian_docs_uploaded_by" FOREIGN KEY ("uploaded_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "guardian_documents" ADD CONSTRAINT "FK_guardian_docs_reviewed_by" FOREIGN KEY ("reviewed_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "guardian_documents" ADD CONSTRAINT "FK_guardian_docs_guardian_id" FOREIGN KEY ("guardian_id") REFERENCES "minor_guardians"("guardian_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "organization_representative_documents" ADD CONSTRAINT "FK_org_rep_docs_uploaded_by" FOREIGN KEY ("uploaded_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "organization_representative_documents" ADD CONSTRAINT "FK_org_rep_docs_reviewed_by" FOREIGN KEY ("reviewed_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "organization_representative_documents" ADD CONSTRAINT "FK_org_rep_docs_rep_id" FOREIGN KEY ("org_representative_id") REFERENCES "organization_representatives"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "representative_documents" ADD CONSTRAINT "FK_rep_docs_uploaded_by" FOREIGN KEY ("uploaded_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "representative_documents" ADD CONSTRAINT "FK_rep_docs_reviewed_by" FOREIGN KEY ("reviewed_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "representative_documents" ADD CONSTRAINT "FK_rep_docs_rep_id" FOREIGN KEY ("representative_id") REFERENCES "representatives"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "client_documents" ADD CONSTRAINT "FK_client_docs_uploaded_by" FOREIGN KEY ("uploaded_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "client_documents" ADD CONSTRAINT "FK_client_docs_reviewed_by" FOREIGN KEY ("reviewed_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "client_documents" ADD CONSTRAINT "FK_client_docs_client_id" FOREIGN KEY ("client_id") REFERENCES "clients"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "loan_documents" ADD CONSTRAINT "FK_loan_documents_loan_id" FOREIGN KEY ("loan_id") REFERENCES "loans"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "loan_documents" ADD CONSTRAINT "FK_loan_docs_uploaded_by" FOREIGN KEY ("uploaded_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "loan_reminders" ADD CONSTRAINT "FK_loan_reminders_schedule" FOREIGN KEY ("schedule_id") REFERENCES "loan_repayment_schedules"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "loan_reminders" ADD CONSTRAINT "FK_loan_reminders_loan" FOREIGN KEY ("loan_id") REFERENCES "loans"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "loan_penalties" ADD CONSTRAINT "FK_penalties_schedule_id" FOREIGN KEY ("schedule_id") REFERENCES "loan_repayment_schedules"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "loan_penalties" ADD CONSTRAINT "FK_penalties_loan_id" FOREIGN KEY ("loan_id") REFERENCES "loans"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "loan_payments" ADD CONSTRAINT "FK_payments_schedule_id" FOREIGN KEY ("schedule_id") REFERENCES "loan_repayment_schedules"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "loan_payments" ADD CONSTRAINT "FK_payments_loan_id" FOREIGN KEY ("loan_id") REFERENCES "loans"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "loan_payments" ADD CONSTRAINT "FK_loan_payments_transaction_id" FOREIGN KEY ("transaction_id") REFERENCES "client_transactions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "loan_payments" ADD CONSTRAINT "FK_loan_payments_recorded_by" FOREIGN KEY ("recorded_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "loan_repayment_schedules" ADD CONSTRAINT "FK_schedules_loan_id" FOREIGN KEY ("loan_id") REFERENCES "loans"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "loans" ADD CONSTRAINT "FK_loans_reviewed_by" FOREIGN KEY ("reviewed_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "loans" ADD CONSTRAINT "FK_loans_disbursed_by" FOREIGN KEY ("disbursed_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "loans" ADD CONSTRAINT "FK_loans_client_id" FOREIGN KEY ("client_id") REFERENCES "clients"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "loans" ADD CONSTRAINT "FK_loans_branch_id" FOREIGN KEY ("branch_id") REFERENCES "branches"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "loans" ADD CONSTRAINT "FK_loans_applied_by" FOREIGN KEY ("applied_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "loans" ADD CONSTRAINT "FK_loans_account_id" FOREIGN KEY ("account_id") REFERENCES "accounts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "remittances" ADD CONSTRAINT "FK_remittances_sending_teller" FOREIGN KEY ("sending_teller_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "remittances" ADD CONSTRAINT "FK_remittances_sending_session" FOREIGN KEY ("sending_session_id") REFERENCES "teller_sessions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "remittances" ADD CONSTRAINT "FK_remittances_sending_branch" FOREIGN KEY ("sending_branch_id") REFERENCES "branches"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "remittances" ADD CONSTRAINT "FK_remittances_receiving_branch" FOREIGN KEY ("receiving_branch_id") REFERENCES "branches"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "remittances" ADD CONSTRAINT "FK_remittances_payout_teller" FOREIGN KEY ("payout_teller_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "remittances" ADD CONSTRAINT "FK_remittances_payout_session" FOREIGN KEY ("payout_session_id") REFERENCES "teller_sessions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "remittances" ADD CONSTRAINT "FK_remittances_cancelled_by" FOREIGN KEY ("cancelled_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "session_denominations" ADD CONSTRAINT "FK_session_denoms_session_id" FOREIGN KEY ("session_id") REFERENCES "teller_sessions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transfers" ADD CONSTRAINT "FK_transfers_debit_tx" FOREIGN KEY ("debit_transaction_id") REFERENCES "client_transactions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transfers" ADD CONSTRAINT "FK_transfers_credit_tx" FOREIGN KEY ("credit_transaction_id") REFERENCES "client_transactions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "client_transactions" ADD CONSTRAINT "FK_client_tx_performed_by" FOREIGN KEY ("performed_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "client_transactions" ADD CONSTRAINT "FK_client_tx_branch_id" FOREIGN KEY ("branch_id") REFERENCES "branches"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "client_transactions" ADD CONSTRAINT "FK_client_tx_account_id" FOREIGN KEY ("account_id") REFERENCES "accounts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "teller_transactions" ADD CONSTRAINT "FK_teller_tx_account_id" FOREIGN KEY ("account_id") REFERENCES "accounts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "teller_transactions" ADD CONSTRAINT "FK_teller_transactions_session" FOREIGN KEY ("session_id") REFERENCES "teller_sessions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "teller_sessions" ADD CONSTRAINT "FK_teller_sessions_teller" FOREIGN KEY ("teller_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "teller_sessions" ADD CONSTRAINT "FK_teller_sessions_branch" FOREIGN KEY ("branch_id") REFERENCES "branches"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "teller_sessions" ADD CONSTRAINT "FK_teller_sessions_approver" FOREIGN KEY ("approved_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "teller_coa_accounts" ADD CONSTRAINT "FK_teller_coa_accounts_usd_coa" FOREIGN KEY ("usd_coa_id") REFERENCES "chart_of_accounts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "teller_coa_accounts" ADD CONSTRAINT "FK_teller_coa_accounts_teller" FOREIGN KEY ("teller_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "teller_coa_accounts" ADD CONSTRAINT "FK_teller_coa_accounts_fc_coa" FOREIGN KEY ("fc_coa_id") REFERENCES "chart_of_accounts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "branch_coa_accounts" ADD CONSTRAINT "FK_bca_vault_usd_coa" FOREIGN KEY ("vault_usd_coa_id") REFERENCES "chart_of_accounts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "branch_coa_accounts" ADD CONSTRAINT "FK_bca_vault_fc_coa" FOREIGN KEY ("vault_fc_coa_id") REFERENCES "chart_of_accounts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "branch_coa_accounts" ADD CONSTRAINT "FK_bca_teller_usd_coa" FOREIGN KEY ("teller_usd_coa_id") REFERENCES "chart_of_accounts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "branch_coa_accounts" ADD CONSTRAINT "FK_bca_teller_fc_coa" FOREIGN KEY ("teller_fc_coa_id") REFERENCES "chart_of_accounts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "branch_coa_accounts" ADD CONSTRAINT "FK_bca_branch_id" FOREIGN KEY ("branch_id") REFERENCES "branches"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_users_branch_id" FOREIGN KEY ("branch_id") REFERENCES "branches"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
