export enum UserRole {
  TELLER = 'TELLER',
  LOAN_OFFICER = 'LOAN_OFFICER',
  LOAN_APPROVER = 'LOAN_APPROVER',
  BRANCH_MANAGER = 'BRANCH_MANAGER',
  HEAD_CASHIER = 'HEAD_CASHIER',
  HQ_MANAGER = 'HQ_MANAGER',
  ADMIN = 'ADMIN',
}
export enum UserStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  PENDING = 'PENDING',
}
