export enum DocumentType {
  ID_SCAN = 'ID_SCAN',
  PASSPORT_PHOTO = 'PASSPORT_PHOTO',
  REGISTRATION_DOC = 'REGISTRATION_DOC',
  OPENING_REQUEST_LETTER = 'OPENING_REQUEST_LETTER',
  PROOF_OF_ADDRESS = 'PROOF_OF_ADDRESS',
  BIOMETRIC_DATA = 'BIOMETRIC_DATA',
  OTHER = 'OTHER',
}

export enum DocumentOwnerType {
  CLIENT = 'CLIENT',
  REPRESENTATIVE = 'REPRESENTATIVE',
  GUARDIAN = 'GUARDIAN',
}
